patch request_by_id for Laozi
bandprotocol/pyband pull request #3
Opened 2021-05-12 06:26 UTC by evilpeach

2021-05-12 11:51 UTC, taobun requested changes

2021-05-12 11:51 UTC, taobun commented on pyband/data.py
> +    result: Result
Optional

2021-05-12 11:53 UTC, thebevrishot requested changes

2021-05-14 05:41 UTC, thebevrishot approved these changes

2021-05-14 07:16 UTC, evilpeach commented
@taobun

2021-05-14 10:11 UTC, taobun approved these changes

2021-05-14 10:11 UTC, merged