[feat] Update to BandChain v3
bandprotocol/pyband pull request #36
Opened 2024-12-17 08:09 UTC by warittornc

2024-12-17 18:19 UTC, RogerKSI commented on pyband/client.py
> +            BroadcastTxRequest(tx_bytes=tx_bytes, mode=BroadcastMode.BLOCK)
block_mode is deprecated for cosmos 0.47+. should we remove it?

2024-12-17 18:22 UTC, RogerKSI commented on pyband/client.py
> +            BroadcastTxRequest(tx_bytes=tx_bytes, mode=BroadcastMode.BLOCK)
update readme.md as well as it still use block mode.

2024-12-23 10:27 UTC, taobun commented on pyband/wallet/signer.py
> +from ..proto.cosmos.tx.signing.v1beta1 import SignMode
Unused import

2024-12-23 10:29 UTC, taobun commented on pyband/cosmos_app.py
> +from .proto.cosmos.tx.signing.v1beta1 import SignMode
this too?

2024-12-26 08:36 UTC, taobun commented on pyband/messages/band/tunnel/v1/__init__.py
> +    MsgUpdateAndResetTunnel,
Please pull the latest version -> (MsgUpdateRoute, MsgUpdateSignalsAndInterval)

2025-01-02 11:15 UTC, RogerKSI commented on pyband/messages/band/tunnel/v1/__init__.py
> +    MsgWithdrawFromTunnel,
think MsgUpdateRoute is still missing. please help recheck.

2025-01-02 11:16 UTC, RogerKSI commented on pyband/messages/band/tunnel/v1/__init__.py
> +    MsgWithdrawFromTunnel,
also MsgUpdateAndResetTunnel is changed name.

2025-01-02 11:18 UTC, RogerKSI commented on pyband/messages/band/tunnel/v1/__init__.py
> +    MsgWithdrawFromTunnel,
msgs file seems correct.  not sure why it doesn't have an error for importing non-exist object.

2025-01-02 11:24 UTC, RogerKSI commented on pyband/messages/band/tss/v1/msgs.py
> +    MsgResetDe as MsgResetDeProto,
it should be `DE`.

2025-01-02 11:24 UTC, RogerKSI commented on pyband/messages/band/tss/v1/msgs.py
> +from pyband.proto.band.tss.v1beta1 import (
folder name for all modules should be v1beta1 (except oracle)? to align with proto.

2025-01-02 11:24 UTC, RogerKSI commented on pyband/messages/band/tss/v1/msgs.py
> +    MsgResetDe as MsgResetDeProto,
seems it's auto-generated. I'm not sure why MsgSubmitDEs got the correct one.

2025-01-03 02:58 UTC, warittornc commented on pyband/messages/band/tss/v1/msgs.py
> +    MsgResetDe as MsgResetDeProto,
its auto-generated, I can manually change it for now

2025-01-03 04:27 UTC, taobun requested changes

2025-01-03 04:27 UTC, taobun commented on pyband/messages/band/feeds/v1beta1/msgs.py
> +        return "/band.bandtss.v1beta1.MsgUpdateParams"
feeds?

2025-01-03 05:10 UTC, RogerKSI commented on pyband/proto/band/oracle/v1/__init__.py
> +# sources: band/oracle/v1beta1/genesis.proto, band/oracle/v1beta1/oracle.proto, band/oracle/v1beta1/query.proto, band/oracle/v1beta1/tx.proto
v1?

2025-01-21 06:31 UTC, taobun approved these changes

2025-01-21 07:21 UTC, RogerKSI approved these changes

2025-01-21 08:04 UTC, merged